### ISSUE TITLE
Improve attribute completion

### ISSUE THREAD

**Issue by davelopez** [davelopez/galaxy-tools-extension#26]
When the attribute completion gets triggered on a tag, all the attributes of the tag are displayed in the completion list by alphabetical order even if some of the attributes are already set.

![CurrentAttrCompletion](https://user-images.githubusercontent.com/46503462/94318126-18818d00-ff88-11ea-9cc4-605d8e0ba85e.png)

It would be ideal that **only the remaining attributes will be suggested**. Also, instead of presenting them in alphabetical order by default, it would be desirable to **order them as they appear defined in the XSD**. This will allow to write them in a more consistent way with the best practices.

**Comment by bgruening** [comment]
xref: https://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html?highlight=order%20#coding-style

**Comment by davelopez** [comment]
Hmm... it seems the order of declaration of attributes in the XSD does not follow the coding style. It would be ideal to make them match, so just updating the XSD in the future will maintain the recommended order. Also, the order of XML elements can be enforced during validation by changing the actual ``<xs:all>`` definition for ``<xs:sequence>``.

**Comment by bgruening** [comment]
Yes, I think its a good idea to update the XSD as well.
