### ISSUE TITLE
Support macro validation

### ISSUE THREAD

**Issue by davelopez** [davelopez/galaxy-tools-extension#6]
The macros referenced by a tool should be expanded before validating against the schema. This process will invalidate the diagnostics locations (line number and position) since the XML file no longer matches the original. For this reason, it may be interesting to treat macro validation as a special validation when the file is saved to disk and keep a lightweight validation during normal file editing.

**Comment by davelopez** [comment]
The first solution for macro validation has been proposed on PR #34 

There are some known limitations in this solution:
- Since the ``galaxy.util.xml_macros.load_with_references`` expect to read all the XML from actual files, the validation can only be done after all files are saved to disk, so no in-memory document validation for now.
- The macro files can not be directly validated against an XSD schema, so they are only checked for syntax errors.
- I am not sure if it is common to import different macro files in the same tool, but in that case, after macro expansion, we can not easily know which macro file was the source of the validation error.

**Comment by bgruening** [comment]
> Since the `galaxy.util.xml_macros.load_with_references` expect to read all the XML from actual files, the validation can only be done after all files are saved to disk, so no in-memory document validation for now.

Can you use https://docs.python.org/3/library/io.html#io.StringIO to circumvent this and pass a fileobject to this function? It seems that etree.parse() can take a file-like-object: https://lxml.de/tutorial.html#the-parse-function

> I am not sure if it is common to import different macro files in the same tool, but in that case, after macro expansion, we can not easily know which macro file was the source of the validation error.

Its not used much, but is used.

**Comment by davelopez** [comment]
> Can you use https://docs.python.org/3/library/io.html#io.StringIO to circumvent this and pass a fileobject to this function? It seems that etree.parse() can take a file-like-object: https://lxml.de/tutorial.html#the-parse-function

Hmm... I am not sure, I think [galaxy.util.xml_macros.load_with_references](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/util/xml_macros.py#L9) expects a proper file path so it can later extract the macros from the parent directory when calling [_import_macros](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/util/xml_macros.py#L18). But probably, we can come up with a new solution in the future.

> Its not used much, but is used.

Again, we can study a better solution in the future or we can just mark the whole ``<macros>`` section with errors instead of only the ``<import>`` in case there are multiple of them.
